### ISSUE TITLE
feedstock is out of sync with PyPi package - hasn't updated to 1.3.3

### ISSUE THREAD

**Issue by owenlamont** [conda-forge/jupyterlab_code_formatter-feedstock#23]
I'm not sure if that auto merge change was supposed to handle this but the feedstock hasn't updated to 1.3.3 in sync with the PyPi package. Should it automatically update or create a PR?

**Comment by xhochy** [comment]
It should automatically create PRs for new releases and also automatically merge them. Somehow it seems the bot tripped over the number of releases on the same day. I hope a single manual PR fixes this.
